export const SUPABASE_URL = 'https://ykkcfhtseavwlgyspugd.supabase.co';
export const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlra2NmaHRzZWF2d2xneXNwdWdkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg3MzYwNzEsImV4cCI6MjA4NDMxMjA3MX0.hRPyjqzhM7XNRWx3zdwwXHhnwAQFMWvEFZW7BBSAR4Q';
